apiVersion: apps/v1
kind: Deployment
metadata:
  name: stdout-node
  labels:
    stdout: stdout-node
spec:
  replicas: 1
  selector:
    matchLabels:
      stdout: stdout-node
  template:
    metadata:
      labels:
        stdout: stdout-node
    spec:
      containers:
      - name: stdout
        image: docker.io/stdout/node:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: stdout-node-service
  labels:
    stdout: stdout-node
spec:
  selector:
    app: stdout-node
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stdout-node-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: fluent-node.test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stdout-node-service
            port:
              number: 3001
